package jdbc.program;

/**
 *
 * @author LENOVO
 */

import java.util.*;
import java.sql.*;
import javax.swing.DefaultListModel;
import jdbc.model.*;
import jdbc.service.*;
import jdbc.program.*;

public class JFrameUtama extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameUtama.class.getName());

    MysqlMahasiswaService service = new MysqlMahasiswaService();
    DefaultListModel<String> dlm;
    
    /**
     * Creates new form JFrameUtama
     */
    public JFrameUtama() {
        initComponents();
        jListId.setModel(new DefaultListModel<>());
        jListName.setModel(new DefaultListModel<>());
        
        jListId.addListSelectionListener(e -> {
            int index = jListId.getSelectedIndex();
            if (index >= 0) {
                jTextFieldID1.setText(((DefaultListModel<String>) jListId.getModel()).getElementAt(index));
                jTextFieldInNama1.setText(((DefaultListModel<String>) jListName.getModel()).getElementAt(index));
                jTextFieldID2.setText(((DefaultListModel<String>) jListId.getModel()).getElementAt(index));
                jTextFieldInNama2.setText(((DefaultListModel<String>) jListName.getModel()).getElementAt(index));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneId = new javax.swing.JScrollPane();
        jListId = new javax.swing.JList<>();
        jScrollPaneName = new javax.swing.JScrollPane();
        jListName = new javax.swing.JList<>();
        jLabelId = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelKelola = new javax.swing.JLabel();
        jButtonTakeAll = new javax.swing.JButton();
        jLabelNama = new javax.swing.JLabel();
        jTextFieldNama = new javax.swing.JTextField();
        jButtonAdd = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jTextFieldID1 = new javax.swing.JTextField();
        jTextFieldID2 = new javax.swing.JTextField();
        jTextFieldInNama1 = new javax.swing.JTextField();
        jTextFieldInNama2 = new javax.swing.JTextField();
        jButtonEdit = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jListId.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneId.setViewportView(jListId);

        jListName.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneName.setViewportView(jListName);

        jLabelId.setText("ID");

        jLabel1.setText("Name");

        jLabelKelola.setText("Kelola Data Mahasiswa");

        jButtonTakeAll.setText("Ambil Semua Data");
        jButtonTakeAll.addActionListener(this::jButtonTakeAllActionPerformed);

        jLabelNama.setText("Nama : ");

        jButtonAdd.setText("Tambahkan");
        jButtonAdd.addActionListener(this::jButtonAddActionPerformed);

        jButtonReset.setText("Reset Indeks");
        jButtonReset.addActionListener(this::jButtonResetActionPerformed);

        jTextFieldID2.setToolTipText("");

        jButtonEdit.setText("Edit");
        jButtonEdit.addActionListener(this::jButtonEditActionPerformed);

        jButtonHapus.setText("Hapus");
        jButtonHapus.addActionListener(this::jButtonHapusActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPaneId, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPaneName, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonTakeAll)
                            .addComponent(jLabelNama)
                            .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAdd)
                            .addComponent(jButtonReset)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldID2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(jTextFieldID1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldInNama1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonEdit))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldInNama2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonHapus))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(jLabelKelola)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelId)
                    .addComponent(jLabel1)
                    .addComponent(jLabelKelola))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPaneId)
                    .addComponent(jScrollPaneName)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonTakeAll)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAdd)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldInNama1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEdit))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldInNama2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHapus))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jButtonReset)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTakeAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTakeAllActionPerformed
        // TODO add your handling code here:
        DefaultListModel<String> idModel = new DefaultListModel<>();
        DefaultListModel<String> nameModel = new DefaultListModel<>();
    
        List<Mahasiswa> list = service.getAll();
        for (Mahasiswa mhs : list) {
            idModel.addElement(String.valueOf(mhs.getId()));
            nameModel.addElement(mhs.getNama());
        }
        jListId.setModel(idModel);
        jListName.setModel(nameModel);
    }//GEN-LAST:event_jButtonTakeAllActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        String nama = jTextFieldNama.getText();
        Mahasiswa mhs = new Mahasiswa(nama);
        service.add(mhs);
        jButtonTakeAll.doClick();
        jTextFieldNama.setText("");
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
        if(jTextFieldID1.getText().isEmpty() || jTextFieldInNama1.getText().isEmpty()){ return; }
        int id = Integer.parseInt(jTextFieldID1.getText());
        String nama = jTextFieldInNama1.getText();
        service.update(new Mahasiswa(id, nama));
        jButtonTakeAll.doClick();
        jTextFieldID1.setText(""); jTextFieldInNama1.setText("");
        jTextFieldID2.setText(""); jTextFieldInNama2.setText(""); // agar auto kosong
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        // TODO add your handling code here:
        if(jTextFieldID2.getText().isEmpty() || jTextFieldInNama2.getText().isEmpty()){ return; }
        int id = Integer.parseInt(jTextFieldID2.getText());
        service.delete(id);
        jButtonTakeAll.doClick();
        jTextFieldID2.setText(""); jTextFieldInNama2.setText("");
        jTextFieldID1.setText(""); jTextFieldInNama1.setText(""); // agar auto kosong
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        service.indexReset();
        jButtonTakeAll.doClick();
    }//GEN-LAST:event_jButtonResetActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrameUtama().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonTakeAll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelKelola;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JList<String> jListId;
    private javax.swing.JList<String> jListName;
    private javax.swing.JScrollPane jScrollPaneId;
    private javax.swing.JScrollPane jScrollPaneName;
    private javax.swing.JTextField jTextFieldID1;
    private javax.swing.JTextField jTextFieldID2;
    private javax.swing.JTextField jTextFieldInNama1;
    private javax.swing.JTextField jTextFieldInNama2;
    private javax.swing.JTextField jTextFieldNama;
    // End of variables declaration//GEN-END:variables
}
